version: '3'

services:
  chatbot-core:
    image: chatbot-core
    environment:
      - REST_API_PORT=5005
      - DIALOGUE_MODEL_DIR=models/dialogue
      - ENABLE_DEBUG=true
      - ENDPOINTS_CONFIG_FILE=config/endpoints.docker.yaml
      - DISABLE_CMD=true
    restart: always
    ports:
      - "5005:5005"