version: '3'

services:
  chatbot-core:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/core:latest
    environment:
      - DIALOGUE_MODEL_DIR=models/dialogue
      - ENABLE_DEBUG=true
      - DISABLE_CMD=true
    networks:
      - chatbot
networks:
    chatbot:
      external: true
