version: '3'

services:
  chatbot-core:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/core:latest
    environment:
      - SOCKET_PORT=5005
      - DIALOGUE_MODEL_DIR=models/dialogue
      - ENABLE_DEBUG=true
      - ENDPOINTS_CONFIG_FILE=config/endpoints.docker.yaml
    ports:
      - "5005:5005"
    networks:
      - chatbot
networks:
    chatbot:
      external: true
