version: '3'

services:
  chatbot-core:
    image: docker.nexus.gpchatbot.archi-lab.io/chatbot/core:${bamboo.inject.commit-hash}
    environment:
      - SOCKET_PORT=5005
      - ENDPOINTS_CONFIG_FILE=config/endpoints.prod.yaml
    ports:
      - "5005:5005"
