version: '3'

services:
  chatbot-core:
    environment:
      - DIALOGUE_MODEL_DIR=models/dialogue
      - ENABLE_DEBUG=true
    networks:
      - chatbot
networks:
    chatbot:
      external: true
