intents:
 - greet:
 - set_form_of_address:
 - set_first_name:
 - set_surname:
 - set_street_address:
 - set_zip_code:
 - set_city:
 - set_phone_number:
 - set_e_mail:
 - is_business_affair:
 - branch_selected:
 - is_own_car_damaged:
 - is_counterpart_insured_at_zurich:
 - is_damage_caused_by_own_car:
 - set_first_name_other_insured_party:
 - set_surname_other_insured_party:
 - set_insurance_number:
 - set_first_name_of_victim:
 - set_last_name_of_victim:
 - set_phone_number_of_victim:
 - set_insurance_number_of_victim:
 - is_insured_party_driver:
 - set_license_plate:
 - set_date_of_damage:
 - set_cause_of_damage:
 - set_damage_location:
 - set_description_of_accident:
 - set_current_location_of_car:
 - set_first_name_insured_party:
 - set_surname_insured_party:
 - set_is_callback_wanted:

actions:
 - utter_default
 - utter_greet
 - utter_set_form_of_address
 - utter_set_first_name
 - utter_set_surname
 - utter_set_street_address
 - utter_set_zip_code
 - utter_set_city
 - utter_set_phone_number
 - utter_set_e_mail
 - utter_is_business_affair
 - utter_branch_selected
 - utter_is_own_car_damaged
 - utter_is_counterpart_insured_at_zurich
 - utter_is_damage_caused_by_own_car
 - utter_set_first_name_other_insured_party
 - utter_set_surname_other_insured_party
 - utter_set_insurance_number
 - utter_set_first_name_of_victim
 - utter_set_last_name_of_victim
 - utter_set_phone_number_of_victim
 - utter_set_insurance_number_of_victim
 - utter_is_insured_party_driver
 - utter_set_license_plate
 - utter_set_date_of_damage
 - utter_set_cause_of_damage
 - utter_set_damage_location
 - utter_set_description_of_accident
 - utter_set_current_location_of_car
 - utter_set_first_name_insured_party
 - utter_set_surname_insured_party
 - utter_set_is_callback_wanted

entities:
 - form_of_address
 - first_name
 - surname
 - address_street
 - address_street_number
 - address_zip_code
 - address_city
 - phone_number
 - e_mail
 - business_affair
 - branch
 - car_is_damaged
 - counterpart_is_insured
 - damage_from_own_car
 - first_name_insured_party
 - surname_insured_party
 - insurance_number
 - first_name_injured_party
 - surname_injured_party
 - phone_number_injured_party
 - insurance_number_injured_party
 - insured_party_is_driver
 - license_plate
 - date_of_damage
 - cause_of_damage
 - damage_location
 - description_of_accident
 - current_location_of_car
 - is_callback_wanted
 - callback_phone_number

slots:
 form_of_address:
  type: text
 first_name:
  type: text
 surname:
  type: text
 address_street:
  type: text
 address_street_number:
  type: text
 address_zip_code:
  type: text
 address_city:
  type: text
 phone_number:
  type: text
 e_mail:
  type: text
 business_affair:
  type: text
 branch:
  type: text
 car_is_damaged:
  type: text
 counterpart_is_insured:
  type: text
 damage_from_own_car:
  type: text
 first_name_insured_party:
  type: text
 surname_insured_party:
  type: text
 insurance_number:
  type: text
 first_name_injured_party:
  type: text
 surname_injured_party:
  type: text
 phone_number_injured_party:
  type: text
 insurance_number_injured_party:
  type: text
 insured_party_is_driver:
  type: text
 license_plate:
  type: text
 date_of_damage:
  type: text
 cause_of_damage:
  type: text
 damage_location:
  type: text
 description_of_accident:
  type: text
 current_location_of_car:
  type: text
 is_callback_wanted:
  type: text
 callback_phone_number:
  type: text
    
templates:
 utter_default:
   - text: "Default text"
 utter_greet:
   - text: "Hi, i am a Bot"
 utter_set_form_of_address:
   - text: "Wie darf ich Sie ansprechen?"
 utter_set_first_name:
   - text: "Wie lautet Ihr Vorname?"
 utter_set_surname:
   - text: "Dankeschön. Wie lautet Ihr Nachname?"
 utter_set_street_address:
   - text: "Wie lautet Ihre Straße und Hausnummer?"
 utter_set_zip_code:
   - text: "Nennen Sie mir bitte Ihre Postleitzahl."
 utter_set_city:
   - text: "In welchem Ort wohnen Sie?"
 utter_set_phone_number:
   - text: "Unter welcher Telefonnummer können wir Sie am besten erreichen?"
 utter_set_e_mail:
   - text: "Wie lautet Ihre E-Mail Adresse?"
 utter_is_business_affair:
   - text: "Handelt es sich bei Ihnen um eine gewerbliche Angelegenheit?"
 utter_branch_selected:
   - text: "In welcher Sparte möchten Sie einen Versicherungsfall melden?"
 utter_is_own_car_damaged:
   - text: "Wurde Ihr eigenes Auto beschädigt?"
 utter_is_counterpart_insured_at_zurich:
   - text: "Ist Ihr Unfallgegner bei der Zurich versichert?"
 utter_is_damage_caused_by_own_car:
   - text: "Wurde der Schaden von Ihrem Auto verursacht?"
 utter_set_first_name_other_insured_party:
   - text: Wie lautet der Vorname des Versicherungsnehmers?
 utter_set_surname_other_insured_party:
   - text: "Wie lautet der Nachname des Versicherungsnehmers?"
 utter_set_insurance_number:
   - text: "Falls vorhanden, wie lautet die Versicherungsnummer des Versicherungsnehmers?"
 utter_set_first_name_of_victim:
   - text: "Wie lautet der Vorname des Geschädigten?"
 utter_set_last_name_of_victim:
   - text: "Wie lautet der Nachname des Geschädigten?"
 utter_set_phone_number_of_victim:
   - text: "Falls vorhanden geben Sie mir bitte die Telefonnummer des Geschädigten."
 utter_set_insurance_number_of_victim:
   - text: "Falls vorhanden bitte auch noch die Versicherungsnummer des Geschädigten."
 utter_is_insured_party_driver:
   - text: "Saßen Sie selbst am Steuer?"
 utter_set_license_plate:
   - text: "Wie lautet das Kennzeichen des geschädigten Autos? (z. B. ZO-E 1234)"
 utter_set_date_of_damage:
   - text: "Wann hat der Schaden stattgefunden?"
 utter_set_cause_of_damage:
   - text: "Was war die Schadensursache? (z. B. Auffahrunfall oder Parkunfall)"
 utter_set_damage_location:
   - text: "Wo hat sich der Schaden ereignet? (z. B. Autobahn, innerorts)"
 utter_set_description_of_accident:
   - text: "Bitte schildern Sie uns kurz den Unfallhergang."
 utter_set_current_location_of_car:
   - text: "Wo kann das Fahrzeug besichtigt werden?"
 utter_set_first_name_insured_party:
   - text: "Wie lautet der Vorname des Versicherungsnehmers?"
 utter_set_surname_insured_party:
   - text: "Wie lautet der Nachname des Versicherungsnehmer?"
 utter_set_is_callback_wanted:
   - text: "Möchten Sie für Rückfragen eine Rückrufnummer bei uns hinterlegen?"
