intents:
- greet:
    use_entities: true
- set_form_of_address:
    use_entities: true
- set_first_name:
    use_entities: true
- set_surname:
    use_entities: true
- set_street_address:
    use_entities: true
- set_zip_code:
    use_entities: true
- set_city:
    use_entities: true
- set_phone_number:
    use_entities: true
- set_e_mail:
    use_entities: true
- is_business_affair:
    use_entities: true
- branch_selected:
    use_entities: true
- is_own_car_damaged:
    use_entities: true
- is_counterpart_insured_at_zurich:
    use_entities: true
- is_damage_caused_by_own_car:
    use_entities: true
- set_first_name_other_insured_party:
    use_entities: true
- set_surname_other_insured_party:
    use_entities: true
- set_insurance_number:
    use_entities: true
- set_first_name_of_victim:
    use_entities: true
- set_last_name_of_victim:
    use_entities: true
- set_phone_number_of_victim:
    use_entities: true
- set_insurance_number_of_victim:
    use_entities: true
- is_insured_party_driver:
    use_entities: true
- set_license_plate:
    use_entities: true
- set_date_of_damage:
    use_entities: true
- set_cause_of_damage:
    use_entities: true
- set_damage_location:
    use_entities: true
- set_description_of_accident:
    use_entities: true
- set_current_location_of_car:
    use_entities: true
- set_first_name_insured_party:
    use_entities: true
- set_surname_insured_party:
    use_entities: true
- set_is_callback_wanted:
    use_entities: true
actions:
- utter_greet
- utter_month
- action_print_test
- action_fallback

## - utter_default um einen default Fallback festzulegen

entities:
  - entityName
  - month

slots:
  entityName:
    type: text
    initial_value: "value"

  month:
    type: text
    initial_value: "Januar"

templates:
  utter_greet:
  - text: "Hi, i am a Bot"

  utter_month:
  - text: "Hi, i am a Bot an know {month}"
  
  ##utter_default:
  ##- text: "Standard default"
  

