intents:
  - greet
  - month

actions:
- utter_greet
- utter_month
- action_print_test
- action_fallback

## - utter_default um einen default Fallback festzulegen

entities:
  - entityName

slots:
  entityName:
    type: text
    initial_value: "value"

templates:
  utter_greet:
  - text: "Hi, i am a Bot"

  utter_month:
  - text: "Hi, i am a Bot an know {example}"
  
  ##utter_default:
  ##- text: "Standard default"
  

