# Custom action endpoint for the bot
action_endpoint:
  url: http://gpb_chatbot-action_1:5055/webhook

nlu:
  url: http://gpb_chatbot-nlu_1:5000

model:
  url: http://gpb_chatbot-model-server_1:8000/models